### ISSUE TITLE
Functions can't access global variables

### ISSUE THREAD

**Issue by lasermtv07** [ShortLang/ShortLang#10] opened 2024-01-27 19:01 UTC
**Describe the bug**
Constants from std.sl wont load

**Erroring code**
```deg2rad deg: {
        &(deg*(π/180))
}
rad2deg rad: {
        &((rad/π)*180)
}

$deg2rad(90)
$rad2deg(3)
```

**Error**
```
  × Runtime Error
   ╭─[1:1]
 1 │ deg2rad deg: {
 2 │     &(deg*(π/180))
   ·            ─┬
   ·             ╰── Variable not found
 3 │ }
   ╰────

```

**Screenshots**
![image](https://github.com/ShortLang/ShortLang/assets/118477750/21979cbe-cdff-4f34-90d9-fd04b2b8e913)

**Comment by FirePlank** [comment] 2024-01-27 19:03
They do load, the issue is that functions cant currently access global scope variables.

**Comment by FirePlank** [comment] 2024-01-30 08:51
Closing this a bit late but a fix was released for this a few days ago already. Please feel free to try it again!

**Closed as completed by FirePlank** 2024-01-30 08:51 UTC
